# Site settings
title: GOAT FUEL
email: hello@goatfuel.uk
description: >-
  GOAT FUEL - Energy for Champions
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://goatfuel.uk" # the base hostname & protocol for your site

# Social media settings
twitter:
  username: drinkgoatpiss
  card: summary_large_image
facebook:
  app_id: # Optional: your Facebook app ID
  publisher: # Optional: your Facebook page URL
  admins: # Optional: Facebook user IDs of admins
logo: /assets/images/goat-logo-transparent.png # Path to your site logo
social:
  name: GOAT FUEL
  links:
    - https://twitter.com/drinkgoatpiss
    - https://www.facebook.com/profile.php?id=61581237703396
    - https://www.instagram.com/drinkgoatpiss

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache/
  - .jekyll-cache/
  - .git/
  - .github/

# Sass configuration
sass:
  sass_dir: _sass
  style: compressed
